name = "Raytracing"
uuid = "38da103c-6e39-4dd2-83ef-ac48b06f016c"
authors = ["Matteo Foglieni <matteo.foglieni16@gmail.com>"]
version = "0.1.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
